#!/usr/bin/env python
import os
import argparse
import telepot
import basilio
import time
import os

class StateMachine:
    Kickstalker, Recordhim, Waitforhim, Playcall, Callhim, Unknown = range(6)
    def __init__(self, bot, basilio):
        self.bot = bot
        self.basilio = basilio
        self.setStates([])
    
    def setStates(self, states):
        self.state_index = -1
        self.states = states

    def progress(self, content):
        self.state_index += 1
        state = self.states[self.state_index]
        self.runState(state, content)

    def runState(self, state, content):
        if state == StateMachine.Kickstalker:
            chat_id = content
            self.bot.sendMessage(chat_id, "Go away stalker !!!")
        elif state == StateMachine.Callhim:
            chat_id = content
            bot.sendMessage(chat_id, "Say something to Basilio")
        elif state == StateMachine.Recordhim:
            chat_id = content
            bot.sendMessage(chat_id, "Recording video...")
            video = basilio.recordHim(number_of_frames=100)
            bot.sendVideo(chat_id, video)
        elif state == StateMachine.Waitforhim:
            chat_id = content
            bot.sendMessage(chat_id, "Waiting for Basilio...")
            is_there = basilio.waitForHim(frames_to_wait=300)
            if is_there:
                bot.sendMessage(chat_id, "He is here")
                self.progress(chat_id)
            else:
                bot.sendMessage(chat_id, "He is not here")

        elif state == StateMachine.Playcall:
            chat_id, file_id = content
            bot.download_file(file_id, '/tmp/hi.ogg')
            basilio.callHim('/tmp/hi.ogg')
            self.progress(chat_id)
            

def handleMsg(msg):
    global state_machine
    global args
    content_type, chat_type, chat_id = telepot.glance(msg) 
    user_id=msg['from']['id']
    if user_id != args.user_id:
        state_machine.setStates([StateMachine.Kickstalker])
        state_machine.progress(chat_id)
        return
    if (content_type == 'text'):
        text    = msg['text']
        if text == '/call':
            state_machine.setStates([StateMachine.Callhim, StateMachine.Playcall, StateMachine.Recordhim])
            state_machine.progress(chat_id)
        if text == '/callandwait':
            state_machine.setStates([StateMachine.Callhim, StateMachine.Playcall, StateMachine.Waitforhim, StateMachine.Recordhim])
            state_machine.progress(chat_id)
    elif (content_type == 'voice'):
            file_id = msg['voice']['file_id']
            state_machine.progress((chat_id, file_id)) 

parser = argparse.ArgumentParser(description='Instagram bot for HAL operations.')
parser.add_argument("token", help="Telegram bot token string as generated by BotFather")
parser.add_argument("user_id", help="Telegram user ID to restrict the bot", type=int)
parser.parse_args()
args = parser.parse_args()


# Getting the token from command-line is better than embedding it in code,
# because tokens are supposed to be kept secret.
bot = telepot.Bot(args.token)
basilio = basilio.Basilio()
state_machine = StateMachine(bot, basilio)
bot.message_loop(handleMsg)
print ('Listening ...')


# Keep the program running.
while 1:
	time.sleep(10)
